// get action 

export const GET_CART_PROGRESS = "GET_CART_PROGRESS"
export const GET_CART_SUCCESS = "GET_CART_SUCCESS"
export const GET_CART_ERROR = "GET_CART_ERROR"

// POST action 

export const POST_CART_PROGRESS = "POST_CART_PROGRESS"
export const POST_CART_SUCCESS = "POST_CART_SUCCESS"
export const POST_CART_ERROR = "POST_CART_ERROR"

// GET final action 
export const GET_FINAL_PROGRESS = "GET_FINAL_PROGRESS"
export const GET_FINAL_SUCCESS = "GET_FINAL_SUCCESS"
export const GET_FINAL_ERROR = "GET_FINAL_ERROR"

// DELETE action 
export const DELETE_FINAL_PROGRESS = "DELETE_FINAL_PROGRESS"
export const DELETE_FINAL_SUCCESS = "DELETE_FINAL_SUCCESS"
export const DELETE_FINAL_ERROR = "DELETE_FINAL_ERROR"

// UPDATE action 
export const UPDATE_FINAL_PROGRESS = "UPDATE_FINAL_PROGRESS"
export const UPDATE_FINAL_SUCCESS = "UPDATE_FINAL_SUCCESS"
export const UPDATE_FINAL_ERROR = "UPDATE_FINAL_ERROR"